### ISSUE TITLE
How do I use URP?

### ISSUE THREAD

**Issue by rtojagic** [psydack/uimgui#14]
Hey, I've read through the docs, but I am unable to setup URP, I just can't find where to add the rendering feature, and there is no Dear Im Gui component.. any help would be greatly appreciated (maybe post screenshots). I am using Unity 2019.

**Comment by psydack** [comment]
Hello there. It seems in 2019 the directive **HAS_URP** is not satisfied because we use version 10+. 

I'm fixing and will update very soon.

Thanks for your feedback.

**Comment by psydack** [comment]
https://github.com/psydack/uimgui/commit/68dfafdf75a40b0dd0b0d2db062d1b7212399c61 fix this. Could you use the version 4.0.1 and see if you can following the instructions below?
**I made a blank project so it can be slightly different from yours**

1- find your renderer and add RenderImGui component on it: 
![image](https://user-images.githubusercontent.com/961971/129964931-88c071b4-cb1e-435c-a3e5-ca4149ec807d.png)

2- add U ImGui Component
![image](https://user-images.githubusercontent.com/961971/129965000-1ade5315-84a5-41f2-b5d9-109789edf9d6.png)

3- change Renderer Type to procedural (just because it's 2019)

4- drag you RenderImGui Component created on your renderer
![image](https://user-images.githubusercontent.com/961971/129965285-75c05284-9728-45a7-9de3-5c4efc95c333.png)

5- add your shader and style (the UImGui package has two default that you can use: **Packages/UImGui/Resources/**)
![image](https://user-images.githubusercontent.com/961971/129965437-073a5937-0fcd-4c77-ac5f-536665b0ac9c.png)

6- (optional) add Show Demo Window Script in your scene 
![image](https://user-images.githubusercontent.com/961971/129965651-13f556a8-4c5f-435e-a9fd-92d05de3c53b.png)

7- (optional) the URP shaders are not working very well with FXAA, so if you're getting an blurry image, you can change to other:
![image](https://user-images.githubusercontent.com/961971/129965785-41adf30b-a452-4979-90b3-384c1cd4acb7.png)

If it fixed your problem, could you close this issue please?
Thanks again.

**Comment by rtojagic** [comment]
Yes, this worked. Thanks a lot! :)

**Comment by charlietran** [comment]
Noting for anyone trying to do this with URP 17 / Unity 6, the steps are different:

1. Add the RenderImGui comonent and Rendering Feature as stated above
2. In the inspector for your Universal Renderer Data asset (the thing to which you just added the Rendering Feature), click the 3 dot menu at the top right (next to the lock icon) and change it from "Normal" to "Debug"
3. Now you should see a "Renderer Features" dropdown, expand that, then right click on the RenderImGui renderer feature and select "Copy"
4. Now go back to the RenderImGui component, right click on the Render Feature input and select "Paste"
5. You will also need to enable RenderGraph compatibility mode at `Project Settings > Graphics > URP > Render Graph > Compatibility Mode (Render Graph Disabled)`. Otherwise you will not see IMGUI render at all.

**Comment by MertBalkan** [comment]
If you're still having trouble setting up Dear ImGui, then after successfully completing the setup steps, you can add the following script define symbols in Unity under **Edit > Project Settings > Player > Script Define Symbols**:

* `UIMGUI_REMOVE_IMPLOT`
* `UIMGUI_REMOVE_IMNODES`
* `UIMGUI_REMOVE_IMGUIZMO`

**Comment by kaelyavel** [comment]
Unity 6000.0.51f1 (Windows 10, Intel I5-10300H, GTX 1650) kept crashing on me despite following all the guidelines in this issue and outside UNTIL I added @MertBalkan Define Symbols.

It works flawlessly now, thank you very much !
