### ISSUE TITLE
Rendering Issue - Topmost

### ISSUE THREAD

**Issue by wh0am15533** [psydack/uimgui#23]
Any suggestions for how to set the rendering/sorting layer? See these one is from the editor and one from injected at runtime.

It seem's UI object's will over-draw the DearImGui window. I've played with the Shader's renderqueue but no change. Any suggestions on how to make it top-most? (It happen's with just Dear ImGui also, same result, but where the hell to set the topmost? I've tried canvas sorting order, Camera depth, renderqueue, layer's, nothing change's it.)

BTW: I also made a fix for URP/HDRP Shader's not included in build's. It allows including into AssetBundles also. Like all those hidden/internal builtin shader's in URP/HDRP.

![Capture](https://user-images.githubusercontent.com/18432559/145327817-cd90d8e6-0b84-42d0-8e9c-45eaf053720c.PNG)

![Capture1](https://user-images.githubusercontent.com/18432559/145327819-c04cee5f-6a4c-4db8-8ae8-c06ecd8d04c6.PNG)

**Comment by psydack** [comment]
Hello! 

You could use different cameras to reach what you're looking for. 
![image](https://user-images.githubusercontent.com/961971/145359017-9b508406-d9ad-424f-932b-dce0a01e6990.png)

You'll need to set your canvas to render into a specific camera:
![image](https://user-images.githubusercontent.com/961971/145359109-0db347ad-6084-4bdf-b36e-7cb8cbed53e5.png)

It's quick test and it works for this set up
Main Camera -> Render UImGui
Main Camera (1) -> Render Canvas UI
Main Camera (2) -> Everything else

**Main Camera**
![image](https://user-images.githubusercontent.com/961971/145359488-57408a08-1bea-4472-9d15-2aff8eed6d7a.png)

**Main Camera (1)**
![image](https://user-images.githubusercontent.com/961971/145359508-52977758-ce92-4202-906f-349b0af23667.png)

Main Camera **(2)**
![image](https://user-images.githubusercontent.com/961971/145359582-b750c378-917d-4f3d-bd17-7ef7089c04ba.png)

It would be awesome if you could make a merge request with your fix or any other way better to share.

**Comment by wh0am15533** [comment]
Thanks for info, that helps alot! 

I started with DearImGui but moved to UImGui due to the added features you have, not to mention your more active on your repo. their's appears dead.

I'll get a PR setup with my changes. Good stuff, I really didn't have to modify the core UIMGui code, Just some changes mainly in uimgui.cs, in order to support bundling it into a an AssetBundle for runtime loading. I was getting issue with missing asset dependencies with URP assets and the Unity Editor wouldn't let you add them After adding a ShaderVariantCollection and prewarming the shader's, the asset's get included. I mainly had to figure out this camera thing.

**Comment by tbarusseau** [comment]
Thanks for sharing, any idea how to replicate this behaviour with URP/HDRP?

For now I'm just toggling off my UI whenever I display my uimgui debug interface. Thanks for the great package by the way.

**Comment by psydack** [comment]
You can do using the same logic as above (I made a quick sample on URP)

![image](https://user-images.githubusercontent.com/961971/147493920-29543547-9310-49ad-b0cc-8b432d09b750.png)

Make 2 more camera using overlay and use the stack feature as described here https://www.youtube.com/watch?v=OmCjPctKkjw

Main Camera
![image](https://user-images.githubusercontent.com/961971/147494033-b5357674-48cb-4777-8425-af49f1fa5cef.png)

UI Camera
![image](https://user-images.githubusercontent.com/961971/147494054-00e7207e-1e6d-48cb-964f-8bcbc9fe93e1.png)

UImGui Camera
![image](https://user-images.githubusercontent.com/961971/147494082-bdf0f4c4-c462-4b25-b527-8ca68256d4f7.png)

Canvas (your UI Canvas)
![image](https://user-images.githubusercontent.com/961971/147494104-552625f7-45de-44d5-b2a3-3d49e346ee55.png)

Hope it helps, otherwise open an issue because other people could get help from there. =)

Thanks for using <3
